version: '3'

tasks:
  run:
    env:
      TAPNCHILL_SERVER: 127.0.0.1:5555
    cmds:
      - go run *.go

  build:
    cmds:
      - docker build -t namhq1989/tapnchill-streaming:latest -t namhq1989/tapnchill-streaming:$(git rev-parse --short HEAD) .
      - docker push namhq1989/tapnchill-streaming:latest
      - docker push namhq1989/tapnchill-streaming:$(git rev-parse --short HEAD)